import fs from 'node:fs'

import { globby } from 'globby'

// Explicit allowlist of exactly what's safe to delete and regenerate from
// scratch — mirrors .gitignore's own entries, plus .husky/_ (regenerated by
// `pnpm install`'s prepare script; Husky ignores it internally rather than
// listing it in .gitignore). Deliberately not `git clean -X`: that also
// honors .git/info/exclude, a local-only ignore file that can list
// machine- or tool-specific folders this script has no business touching.
export const CLEAN_GLOBS = [
  'node_modules',
  'packages/*/*/node_modules',
  'dist',
  'packages/*/*/dist',
  '.turbo',
  'packages/*/*/.turbo',
  '.eslintcache',
  '.prettiercache',
  // Mirrors typecheck-extras.ts's own tsconfig discovery (its FIXED_TSCONFIGS
  // plus per-package e2e/bench globs), each with its generated build info
  // suffix - explicit paths, not a `**` glob, so there's no need for a
  // node_modules exclusion that could (and once did) also swallow the
  // `node_modules` cleanup entry above via fast-glob's negation semantics.
  'tsconfig.tooling.json.tsbuildinfo',
  'tsconfig.esm-strict.json.tsbuildinfo',
  'scripts/tsconfig.json.tsbuildinfo',
  'e2e/tsconfig.json.tsbuildinfo',
  'packages/*/*/e2e/tsconfig.json.tsbuildinfo',
  'packages/*/*/bench/tsconfig.json.tsbuildinfo',
  'packages/*/*/temp',
  'coverage',
  'reports',
  'test-results',
  'playwright-report',
  'blob-report',
  '.stryker-tmp',
  'sbom',
  'results.sarif',
  'bench-baseline.json',
  '.husky/_'
]

export async function clean(): Promise<void> {
  // expandDirectories: false — otherwise a bare directory name like
  // `coverage` expands into `coverage/**`, matching every file inside
  // instead of the directory itself.
  const matches = await globby(CLEAN_GLOBS, {
    onlyFiles: false,
    gitignore: false,
    dot: true,
    expandDirectories: false
  })

  for (const match of matches) {
    fs.rmSync(match, { recursive: true, force: true })
  }
}
