import ts from 'typescript'

export interface StripResult {
  source: string
  // Qualified names ("describe title(s) + it title", space-joined, matching
  // how Vitest reports a nested test's full name) that were actually found
  // and removed. Compare against the names passed in — any name NOT in
  // this list wasn't found as a plain `it(...)`/`test(...)` call (most
  // commonly because it's generated by `it.each(...)`, which this
  // deliberately never touches: removing one row from a table without
  // corrupting the array literal needs real judgment, not a codemod).
  removed: string[]
}

/**
 * Removes plain `it(...)`/`test(...)` statements (never `it.each`/
 * `test.each`, which this deliberately leaves untouched — see
 * {@link StripResult.removed}) whose fully-qualified name (every
 * enclosing `describe` title, space-joined, followed by the test's own
 * title) matches one of `qualifiedNames`. A `describe` title can be a
 * string literal or a bare identifier (`describe(SomeFunction, ...)`,
 * matching this repo's `vitest/prefer-describe-function-title` — the
 * identifier's own text is used, matching how Vitest resolves the
 * function/class's `.name` at runtime).
 *
 * @public
 */
export function stripTests(source: string, qualifiedNames: Set<string>): StripResult {
  const sourceFile = ts.createSourceFile(
    'input.ts',
    source,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TS
  )

  const removalSpans: { start: number; end: number }[] = []
  const removed = new Set<string>()
  const describeStack: (string | undefined)[] = []

  function literalText(node: ts.Node): string | undefined {
    if (ts.isStringLiteralLike(node)) return node.text
    if (ts.isIdentifier(node)) return node.text

    return undefined
  }

  function visit(node: ts.Node) {
    if (ts.isExpressionStatement(node) && ts.isCallExpression(node.expression)) {
      const callee = node.expression.expression

      if (ts.isIdentifier(callee) && callee.text === 'describe') {
        const firstArg = node.expression.arguments[0]
        const title = firstArg ? literalText(firstArg) : undefined

        describeStack.push(title)
        ts.forEachChild(node, visit)
        describeStack.pop()

        return
      }

      if (ts.isIdentifier(callee) && (callee.text === 'it' || callee.text === 'test')) {
        const firstArg = node.expression.arguments[0]
        const itTitle = firstArg ? literalText(firstArg) : undefined
        const qualified = [...describeStack, itTitle].filter((part) => part !== undefined).join(' ')

        if (itTitle !== undefined && qualifiedNames.has(qualified)) {
          removed.add(qualified)
          removalSpans.push({ start: node.getFullStart(), end: node.getEnd() })

          return
        }
      }
    }

    ts.forEachChild(node, visit)
  }

  visit(sourceFile)

  removalSpans.sort((a, b) => a.start - b.start)

  let result = ''
  let cursor = 0

  for (const { start, end } of removalSpans) {
    result += source.slice(cursor, start)
    cursor = end
  }

  result += source.slice(cursor)

  return { source: result, removed: [...removed] }
}
