export type { AuthConfig } from '@codeminity/request-core'
export { TokenModeEnum } from '@codeminity/request-core'

export { createFetch } from './create'
export type { CallbackConfig } from './shared/callback-config.interface'
export type { Config } from './shared/config.interface'
export type { ErrorEvent } from './errors/error-event.type'
export { ErrorEventEnum } from './errors/error-event.enum'
export type { FetchOutcome } from './errors/fetch-outcome.interface'
export type { FetchRequestInit, RequestConfig } from './shared/request-config.interface'
export type { RetryConfig } from './retry/retry-config.interface'
