export type { AuthConfig } from '@codeminity/request-core'
export { TokenModeEnum } from '@codeminity/request-core'

export { createFetch } from './create.js'
export type { CallbackConfig } from './shared/callback-config.interface.js'
export type { Config } from './shared/config.interface.js'
export type { ErrorEvent } from './errors/error-event.type.js'
export { ErrorEventEnum } from './errors/error-event.enum.js'
export type { FetchOutcome } from './errors/fetch-outcome.interface.js'
export type { FetchRequestInit, RequestConfig } from './shared/request-config.interface.js'
export type { RetryConfig } from './retry/retry-config.interface.js'
